/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gist.test;

public class App  {

    private String data() {
        return "data";
    }

    public String execute() {
        String o = data();
        o = o.toUpperCase();
        System.out.println("Find DATA." + (data().equals(o)));
        return o;
    }

    public static void main(String[] args) {
        new App().execute();
    }
}
