/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gist.spring;

import org.springframework.expression.Expression;
import org.springframework.expression.spel.standard.SpelExpressionParser;

public class SpelExpIT {
    private final SpelExpressionParser parser = new SpelExpressionParser();

    private void testInList() {
        test("{1,2,3}.contains(5)");
        test("{1,2,3}.contains(2)");
        test("{1,2,3}.contains(2) AND false");
        test("{1,2,3}.contains(3)");
        test("{1,2,3}.size() == 3");
        test("{1,1,2,2,3,3,3}.stream().distinct().count() > 3");
    }

    void test(String val) {
        Expression exp = parser.parseExpression(val);
        Object message = exp.getValue();
        System.out.println(val + " =>" + message);
    }

    public static void main(String[] args) {
        new SpelExpIT().testInList();
    }
}
