/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gist.test;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;


public class AppTest {

    @Test
    public void execute() {
        App classUnderTest = new App();
        System.out.println("Running AppTest..");
        assertEquals("DATA", classUnderTest.execute(), "Did not match DATA.");
    }

    @Test public void testFoo() {
        assertTrue(true);
    }

}
